---

- name: precompile assets # noqa 301
  command: bash -lc "bundle exec rake assets:precompile RAILS_ENV={{ rails_env }}"
  args:
    chdir: "{{ build_path }}"
  become: yes
  become_user: "{{ unicorn_user }}"
