---

domain: staging.openfoodnetwork.org.pl
host_id: pl-staging # country initials (eg uk, es, de) and environment (default is prod)
rails_env: staging

admin_email: marcin.sawinski@protonmail.com

mail_domain: kooplab.org

# Optional list of subdomains to register in letsencrypt certificate
# Defaults to {{ domain }} if list is undefined
#
#certbot_domains:
#  - example.com
#  - www.example.com
#  - info.example.com

# Size in bytes. You can also use units like 1G, 512MiB or 1000KB. See: `man fallocate`
# The default is `false`, not installing a swapfile.
#swapfile_size: 1G

# Enable external database access for third party integrations
postgres_listen_addresses:
  - '*'
#
#custom_hba_entries:
#  - { type: host, database: "{{ all }}", user: all, adress: 'openfoodnetwork.org.pl/32', auth_method: md5 }
#  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }#
#custom_application_env_vars: |
#  OFN_FEATURE_CONNECT_AND_LEARN: "true"

# Overridable Image Settings
# If you update attachment_styles, you will need to regenerate thumbnails. Use rake paperclip:refresh:thumbnails CLASS=Spree::Image
# attachment_styles:
# attachment_url:
# attachment_path:
# attachment_default_style:
# attachment_default_url:

